### ISSUE TITLE
Cпринт 12.03.19-19.03.19

### ISSUE THREAD

**Issue by bespoyasov** [open-tech-authors/solid#11]
- [ ] сделать конспект по Мартину https://github.com/open-tech-authors/solid/issues/17
- [ ] добавить Мартина в текст https://github.com/open-tech-authors/solid/issues/16
- [x] mdx provider code => Code https://github.com/open-tech-authors/solid/issues/15
- [x] перенести текст из гуглдоков в код https://github.com/open-tech-authors/solid/issues/14
- [x] адаптив к сетке на гридах https://github.com/open-tech-authors/solid/issues/13
- [x] подумать над дизайном меню https://github.com/open-tech-authors/solid/issues/12
- [ ] подключить mobx-state-tree https://github.com/open-tech-authors/solid/issues/18
